namespace SharedSpaces.Server.Domain;

public class SpaceItem
{
    private Guid _id;

    private SpaceItem()
    {
    }

    public SpaceItem(Guid id)
    {
        Id = id;
    }

    // SpaceItem IDs are client-generated by design, so the entity rejects empty GUIDs instead of generating one server-side.
    public Guid Id
    {
        get => _id;
        set => _id = value != Guid.Empty
            ? value
            : throw new ArgumentException("Space item ID must be a non-empty GUID.", nameof(value));
    }

    public Guid SpaceId { get; set; }
    public Guid MemberId { get; set; }
    public string ContentType { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public long FileSize { get; set; }
    public DateTime SharedAt { get; set; } = DateTime.UtcNow;
    public Space Space { get; set; } = null!;
    public SpaceMember Member { get; set; } = null!;
}
